version: '3.8'

services:
  dash-estoque:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash-estoque
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
      # Adicione suas variáveis de ambiente aqui
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

